ar2_arm:
  hardware_interface:
    loop_hz: 20 # hz
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    steps_per_degree: [44.705882, 55.303030, 56.071429, 46.060606, 21.785714, 21.370968]
    speed_rate: 25
    acc_duration: 15
    acc_rate: 10
    dec_duration: 20
    dec_rate: 5
    hardware: 'rosserial'
    rosserial:
      topic: '/arm_hardware_interface'
    serial:
      port: '/dev/ttyACM0'
      baudrate: 57600
