ar2_arm:
  controllers:
    stop_trajectory_duration: 0.0 # sec
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    command:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      constraints:
        goal_time: 20.0
        stopped_velocity_tolerance: 0.01 # 0.01 rad/s
        joint_1:
          trajectory: 2.0
          goal: 0.01
        joint_2:
          trajectory: 2.0
          goal: 0.01
        joint_3:
          trajectory: 2.0
          goal: 0.01
        joint_4:
          trajectory: 2.0
          goal: 0.01
        joint_5:
          trajectory: 2.0
          goal: 0.01
        joint_6:
          trajectory: 2.0
          goal: 0.01
