ar2_arm:
  controllers:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 20
    position:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      constraints:
        goal_time: 0.5
        joint_1:
          trajectory: 0.5
          goal: 0.4
        joint_2:
          trajectory: 1.0
          goal: 0.65
        joint_3:
          trajectory: 1.5
          goal: 1.0
        joint_4:
          trajectory: 0.5
          goal: 0.02
        joint_5:
          trajectory: 1.5
          goal: 0.8
        joint_6:
          trajectory: 0.5
          goal: 0.2
