ar2_arm:
  hardware_interface:
    loop_hz: 20 # hz
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    steps_per_degree: [44.705882, 110.60606, 56.071429, 46.060606, 21.785714, 42.741936]
    forward_dir: [1, 1, 1, -1, 1, 1]
    home_offsets: [160, 41, -149, -78.5, 91.5, -163]
    home_kinematics: [100, 5, 25, 5, 25] # order speed_rate-acc_dur-acc_rate-dcc_dur-dcc_rate
    speed_rate: 100
    acc_duration: 15
    acc_rate: 10
    dec_duration: 20
    dec_rate: 5
    hardware: 'rosserial'
    rosserial:
      topic: '/arm_hardware_interface'
    serial:
      port: '/dev/ttyACM0'
      baudrate: 115200
